### ISSUE TITLE
vs code solidity plugin

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/OptimismTemplate#1]
For some reason, my vscode plugin is not the same as the screen capture shown and is not using the config setting(to use node installed solc but always go to remote)

any reason why ? environment is Windows 10, VS code 1.46.1 and solidity plugin 0.076

**Comment by garyng2000** [comment]
any chance I am using an old version of the plugin ? the context manual looks so different. I only have 3 option(change global remote/local remote and get solidity release.

strangely, if I install the plain nodejs version of solc, the plugin seems to know to use that instead of remote. making me think that my version is not the same version as shown in the screen but that is the newest I can find, which say released 7 months ago.

**Comment by garyng2000** [comment]
ah, so I have to update my vscode as well in order to see the newer version of plugin, problem solved.

**Comment by juanfranblanco** [comment]
@garyng2000  glad you are sorted, hopefully you like the new features. !!

**Comment by garyng2000** [comment]
yes it helps a lot for this dual compiler requirement :-)
