### ISSUE TITLE
L2DepositedERC20Deployment didn't work right way

### ISSUE THREAD

**Issue by kevinlai219** [Nethereum/OptimismTemplate#5]
ERC20_L1_to_L2_Deposit_and_Withdraw.cs

When I tried to test ERC20_L1_to_L2_Deposit_and_Withdraw.cs, I found that L2DepositedRC20Deployment didn't work right way.
Actually, L2DepositedERC20.sol contracts is inherited ERC20.sol and when the initialSupply is initialized as 0 in L2DepositedERC20.
However, after running the deploying code, and get the deployed smart contracts address, then import token with that address into wallet.
It is not 0, but random number I think.
![image](https://user-images.githubusercontent.com/93578592/153123904-2905a5e8-ca23-47a8-9cea-ea60cc05dcd9.png)

Is there any problem?
In this test, I used 

L1 as https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
L2 as https://kovan.optimism.io

Another weird thing is receipt .DecodeAllEvents can't catch any event so that count = 0.

So I think these factors occur this exception.
![image](https://user-images.githubusercontent.com/93578592/153124568-8d1d63b4-7175-40bd-904c-490ac6d15065.png)

**Comment by kevinlai219** [comment]
Thx! Mr. Juan
I think there's a problem with sending message, 
I tried to another test, 'StorageCrossPlatformTests.cs', but still same error.
In "ERC20_L1_to_L2_Deposit_and_Withdraw.cs"

var receiptDeposit = await gatewayService.DepositRequestAndWaitForReceiptAsync(new DepositFunction() { Amount = 1, Gas = 7000000 });

In "StorageCrossPlatformTests.cs"

 var messageTransactionReceipt = await l2CrossDomainMessengerService.SendMessageRequestAndWaitForReceiptAsync(message);


After running that code lines, "watcher.GetMessagesHashes" can't catch sent messages.

**Comment by kevinlai219** [comment]
Hi, Mr. Juan
Please consider the deploying smart contracts to Layer2.
I tried to deploy ERC20 Contracts to Layer2 with hardhat, and used testchain (localhost:8545), but also there seems be random number of tokens 1743280005859429580717715935127017118905506969531736240423467206075712395313....

So I am just curious that the Layer 2 is all right?

**Comment by kevinlai219** [comment]
Hi, Mr.Juan
Hope you are doing well.
Please inform me if there's any update.
It's really necessary for me and for all nethereum fans.

**Comment by kevinlai219** [comment]
Hi, Juan
Any updates?

**Comment by juanfranblanco** [comment]
@kevinlai219 updated now have a look

**Comment by kevinlai219** [comment]
Thanks Juan.
Thanks for your effort.
I will have a look on it right now.

**Comment by juanfranblanco** [comment]
Test it on Kovan, most contracts have changed, so it is much easier to get started now.

**Comment by kevinlai219** [comment]
Hi, Juan
I have tested new code you pushed, and it works very good.
Thanks.

Kevin
