### ISSUE TITLE
Deploy a contract to Optimism failed.

### ISSUE THREAD

**Issue by fseffert** [Nethereum/OptimismTemplate#6]
Hi guys... I wrote a simple contract that I want to deploy on optimism. So I did install a local environment with a L1 and L2 node on Docker like in the Optimism documentation: https://community.optimism.io/docs/developers/build/dev-node/

First, I tried on layer 1:

`var privateKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
var account = new Nethereum.Web3.Accounts.Account(privateKey, 31337);
layer1 = new Web3(account, "http://localhost:9545");
var x = await T_01.Contracts.T01Message.T01MessageService.DeployContractAndGetServiceAsync(layer1,
   new Contracts.T01Message.ContractDefinition.T01MessageDeployment());`

This worked like a charm and the contract was successfully deployed! Then I tried on layer 2 with the exact same code snippet except the node and chain id:

`var privateKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
var account = new Nethereum.Web3.Accounts.Account(privateKey, 420);
layer2 = new Web3(account, "http://localhost:8545");
var x = await T_01.Contracts.T01Message.T01MessageService.DeployContractAndGetServiceAsync(layer2,
   new Contracts.T01Message.ContractDefinition.T01MessageDeployment());`

...but that is raising an error: **Nethereum.JsonRpc.Client.RpcResponseException: rlp: expected input list for types.txdata: eth_sendRawTransaction**

Can you tell me what I do wrong?

**Comment by juanfranblanco** [comment]
Hi, L2 will require to be in LegacyMode as it does not support EIP1559.  You can set it in web3.Eth.TransactionManager.

**Comment by fseffert** [comment]
Thank you... that fixed my issue! --> **layer2.TransactionManager.UseLegacyAsDefault = true;**
